export const locale_en_th: Record<string, [string, string]> = {
  Add: ["Add", "เพิ่ม"],
  Added: ["Added", "เพิ่มแล้ว"],
  AddedName: ["{{name}} Added", 'เพิ่ม "{{name}}" แล้ว'],
  AddName: ["Add {{name}}", "เพิ่ม{{name}}"],
  "Add Answer": ["Add Answer", "เพิ่มคำตอบ"],
  "Add Choice": ["Add Choice", "เพิ่มตัวเลือก"],
  "Add Highlight": ["Add Highlight", "เพิ่มไฮไลท์"],
  "Add Matching": ["Add Matching", "เพิ่มการจับคู่"],
  "Add Panel": ["Add Panel", "เพิ่มกรอบ"],
  "Add Question": ["Add Question", "เพิ่มข้อสอบ"],
  "Add Slide": ["Add Slide", "เพิ่มสไลด์"],
  Administrator: ["Administrator", "ผู้ดูแลระบบ"],
  Album: ["Album", "อัลบั้ม"],
  Albums: ["Albums", "อัลบั้ม"],
  Align: ["Align", "จัดเรียง"],
  Amount: ["Amount", "จำนวน"],
  AmountOf$Name: ["Amount of {{name}}", "จำนวน{{name}}"],
  Answer: ["Answer", "คำตอบ"],
  "Answer Text": ["Answer Text", "ข้อความคำตอบ"],
  Appearance: ["Appearance", "การแสดงผล"],
  Assignment: ["Assignment", "งานที่มอบหมาย"],
  AttachFiles: ["Attach Files", "แนบเอกสาร"],
  Attemps: ["Attemps", "ครั้งที่ทำได้"],
  Back: ["Back", "กลับ"],
  Book: ["Book", "หนังสือ"],
  Box: ["Box", "กล่อง"],
  Bottom: ["Bottom", "ล่าง"],
  Browse: ["Browse", "เลือกไฟล์"],
  Cancel: ["Cancel", "ยกเลิก"],
  Categories: ["Categories", "หมวดหมู่"],
  Card: ["Card", "การ์ด"],
  Center: ["Center", "กลาง"],
  Change: ["Change", "เปลี่ยน"],
  "Change $Name": ["Change {{name}}", "เปลี่ยน{{name}}"],
  ChangeLanguage: ["Change Language", "เปลี่ยนภาษา"],
  "Change title": ["Change title", "แก้ไขชื่อ"],
  "Change Image": ["Change Image", "เปลี่ยนรูปภาพ"],
  Choice: ["Choice", "ตัวเลือก"],
  Choose: ["Choose", "เลือก"],
  Choose$Name: ["Choose {{name}}", "เลือก{{name}}"],
  "Choose Image": ["Choose Image", "เลือกรูปภาพ"],
  Class: ["Class", "คาบเรียน"],
  Clear: ["Clear", "ล้าง"],
  Close: ["Close", "ปิด"],
  ClosePath: ["Close Path", "ปิดเส้นทาง"],
  Collection: ["Collection", "คอลเล็คชัน"],
  Component: ["Component", "ส่วนประกอบ"],
  Composition: ["Composition", "จัดองค์ประกอบภาพ"],
  Confirm: ["Confirm", "ยืนยัน"],
  "Confirm Password": ["Confirm Password", "ยืนยันรหัสผ่าน"],
  "Convert to $Name": ["Convert to {{name}}", "แปลงเป็น{{name}}"],
  "Collaborated Courses": ["Collaborated Courses", "หลักสูตรที่ร่วมสอน"],
  "Collaborated Teacher": ["Collaborated Teacher", "ผู้ร่วมสอน"],
  Course: ["Course", "หลักสูตร"],
  "Course Manager": ["Course Manager", "จัดการหลักสูตร"],
  Cover: ["Cover", "ภาพปก"],
  "Create $Name": ["Create {{name}}", "สร้าง{{name}}"],
  Created: ["Created !", "สร้างแล้ว !"],
  Dark: ["Dark", "มืด"],
  DarkMode: ["Dark Mode", "ธีมสีเข้ม"],
  Date: ["Date", "วันที่"],
  Detail: ["Detail", "รายละเอียด"],
  Description: ["Description", "รายละเอียด"],
  Deselect: ["Deselect", "ยกเลิกการเลือก"],
  DisplayName: ["Display Name", "ชื่อที่ใช้แสดง"],
  "Display Name": ["Display Name", "ชื่อที่แสดง"],
  Divider: ["Divider", "เส้นแบ่ง"],
  "Do you want to remove?": ["Do you want to remove ?", "คุณต้องการลบหรือไม่?"],
  DoYouWantToRemove: [
    'Do you want to remove "{{name}}" ?',
    'คุณต้องการลบ "{{name}}" หรือไม่?',
  ],
  DoYouWantToRemoveNameForever: [
    `Do you want to remove "{{name}}" forever?`,
    `คุณต้องการลบ "{{name}}" ถาวรใช่หรือไม่?`,
  ],
  Download: ["Download", "ดาวน์โหลด"],
  "Due Date": ["Due Date", "กำหนดส่ง"],
  DropFileHere: ["Drop file here !", "ลากไฟล์ลงที่นี่ !"],
  Dmatching: [
    "Match the answers to the questions.",
    "ให้จับคู่ตัวเลือกกับคำถามให้ถูกต้อง",
  ],
  Dmultiple: ["Choose to best answer.", "ให้เลือกคำตอบที่ถูกต้องที่สุด"],
  Dsorting: ["Sorting the answer options.", "ให้เรียงลำดับตัวเลือกให้ถูกต้อง"],
  Dtruefalse: [
    "Identify if the following true or false.",
    "ให้เลือกว่าข้อความที่ให้มาถูกหรือผิด",
  ],
  Edit: ["Edit", "แก้ไข"],
  Edit$Name: ["Edit {{name}}", "แก้ไข{{name}}"],
  Email: ["Email", "อีเมล"],
  Empty: ["Empty", "ว่างเปล่า"],
  End: ["End", "สิ้นสุด"],
  English: ["English", "อังกฤษ"],
  Error: ["Error", "เกิดข้อผิดพลาด"],
  False: ["False", "ผิด"],
  FeatureImage: ["Feature Image", "ภาพปก"],
  FEEDS: ["FEEDS", "ฟีดส์"],
  Female: ["Female", "หญิง"],
  File: ["File", "ไฟล์"],
  Filter: ["Filter", "ตัวกรอง"],
  "First Name": ["First Name", "ชื่อ"],
  "Forget Password": ["Forget Password", "ลืมรหัสผ่าน"],
  From: ["From", "จาก"],
  "From URL": ["From  URL", "จาก URL"],
  Gender: ["Gender", "เพศ"],
  Grade: ["Grade", "เกรด"],
  Grading: ["Grading", "ตัดเกรด"],
  Header: ["Header", "หัวเรื่อง"],
  Heading: ["Heading", "หัวเรื่อง"],
  Height: ["Height", "สูง"],
  Hide: ["Hide", "ซ่อน"],
  "Hide Toolbar": ["Hide Toolbar", "ซ่อนแถบเครื่องมือ"],
  Highlight: ["Highlight", "ไฮไลท์"],
  Home: ["Home", "หน้าแรก"],
  Horizontal: ["Horizontal", "แนวนอน"],
  ID: ["ID", "รหัส"],
  Inbox: ["Inbox", "กล่องข้อความ"],
  Image: ["Image", "รูปภาพ"],
  Images: ["Images", "รูปภาพ"],
  "Import $Name": ["Import {{name}}", "นำเข้า{{name}}"],
  "Insert After": ["Insert After", "แทรกด้านหลัง"],
  "Insert Before": ["Insert Before", "แทรกก่อนหน้า"],
  "Invalid Email": ["Invalid E-mail", "รูปแบบอีเมลไม่ถูกต้อง"],
  Invite: ["Invite", "เชิญ"],
  "Invite $Name": ["Invite {{name}}", "เชิญ{{name}}"],
  "Regardless Real Score": ["Regardless Real Score", "ไม่พิจารณาคะแนนจริง"],
  Language: ["Language", "ภาษา"],
  LastModified: ["Last Modified", "ปรับปรุงล่าสุด"],
  "Last Name": ["Last Name", "สกุล"],
  Lated: ["Lated", "ล่าช้า"],
  Left: ["Left", "ซ้าย"],
  Lesson: ["Lesson", "บทเรียน"],
  "Lesson Content": ["Lesson Content", "เนื้อหาบทเรียน"],
  Level: ["Level", "ระดับ"],
  Light: ["Light", "สว่าง"],
  Line: ["Line", "ไลน์"],
  "Line Application": ["Line Application", "แอปพลิเคชันไลน์"],
  Loading: ["Loading", "กำลังโหลด"],
  "No title": ["No title", "ไม่มีชื่อเรื่อง"],
  Male: ["Male", "ชาย"],
  "Manage $Name": ["Manage {{name}}", "จัดการ{{name}}"],
  "Manage Student": ["Manage Student", "จัดการผู้เรียน"],
  "Match Item": ["Match Item", "คู่ที่"],
  Material: ["Material", "สื่อการเรียนการสอน"],
  Matching: ["Matching", "จับคู่"],
  Menu: ["Menu", "เมนู"],
  Message: ["Message", "ข้อความ"],
  "Middle Name": ["Middle Name", "ชื่อกลาง"],
  More: ["More", "อื่น ๆ"],
  "Move Up": ["Move Up", "เลื่อนขึ้น"],
  "Move Down": ["Move Down", "เลื่อนลง"],
  "Multiple Choice": ["Multiple Choice", "หลายตัวเลือก"],
  "My $Name": ["My {{name}}", "{{name}}ของฉัน"],
  "My Course": ["My Course", "หลักสูตรของฉัน"],
  Name: ["Name", "ชื่อ"],
  "$Name Added": ["{{name}} Added", "เพิ่ม{{name}}แล้ว"],
  $NameName: ["{{name}} name", "ชื่อ{{name}}"],
  NameHasRemoved: ["{{name}} has removed", "{{name}} ได้ถูกลบแล้ว"],
  $NameNotFound: ["{{name}} not found", "ไม่พบ{{name}}"],
  $NameRemoved: ["{{name}} removed", "ลบ{{name}}แล้ว"],
  "$Name Review": ["{{name}} Review", "ตรวจ{{name}}"],
  "$Name Selected": ["{{name}} rows selected", "เลือกจำนวน {{name}} แถว"],
  NameTitle: ["Title", "คำนำหน้า"],
  Next: ["Next", "ต่อไป"],
  No: ["No", "ไม่ใช่"],
  "No Data": ["No Data", "ไม่พบข้อมูล"],
  "No rows": ["No rows", "ไม่มีข้อมูล"],
  "No Title": ["No Title", "ไม่มีชื่อเรื่อง"],
  "$Name not found": ["{{name}} not found", "ไม่พบ{{name}}"],
  Number: ["Number", "ตัวเลข"],
  NumberOf$Name: ["Number of {{name}}", "จำนวน{{name}}"],
  Organize: ["Organize", "องค์กร"],
  Open: ["Open", "เปิด"],
  Other: ["Other", "อื่นๆ"],
  Paragraph: ["Paragraph", "ย่อหน้า"],
  Password: ["Password", "รหัสผ่าน"],
  photos: ["photos", "รูป"],
  Preview: ["Preview", "ดูตัวอย่าง"],
  Prev: ["Previous", "ย้อนกลับ"],
  PleaseWait: ["Please wait", "กรุณารอสักครู่"],
  Private: ["Private", "ส่วนตัว"],
  "Profile Image": ["Profile Image", "รูปประจำตัว"],
  Project: ["Project", "โครงการ"],
  Public: ["Public", "สาธารณะ"],
  Question: ["Question", "คำถาม"],
  "Question Bank": ["Question Bank", "คลังแบบทดสอบ"],
  "Question Title": ["Question Title", "ชื่อข้อสอบ"],
  "Question Type": ["Question Type", "ประเภทคำถาม"],
  Quiz: ["Online Quiz", "แบบทดสอบออนไลน์"],
  Ratio: ["Ratio", "สัดส่วน"],
  ReadyToEdit: [`Ready to edit "{{name}}"?`, `เริ่มสร้าง "{{name}}" เลยไหม?`],
  Right: ["Right", "ขวา"],
  "Rows per page": ["Rows per page", "จำนวนแถวต่อหน้า"],
  Read: ["Read", "อ่าน"],
  Redo: ["Redo", "ทำอีกครั้ง"],
  Register: ["Register", "สมัคร"],
  Remove: ["Remove", "ลบ"],
  Removed: ["Removed", "ลบแล้ว"],
  RemoveLastPoint: ["Remove Last Point", "ลบจุดสุดท้าย"],
  Remove$Name: ["Remove {{name}}", "ลบ{{name}}"],
  Rename: ["Rename", "เปลี่ยนชื่อ"],
  Reverse: ["Reverse", "กลับด้าน"],
  "Right Answer": ["Right answer", "คำตอบที่ถูกต้อง"],
  RowPerPage: ["RowPerPage", "จำนวนแถวต่อหน้า"],
  Save: ["Save", "บันทึก"],
  SaveBeforeLeave: [
    "Would you like to the save the changes before leaving this page?",
    "คุณต้องการบันทึกการแก้ไขก่อนออกจากหน้านี้หรือไม่?",
  ],
  Saved: ["Saved", "บันทึกสำเร็จ"],
  "Send Email": ["Send E-mail", "ส่งอีเมล"],
  SetAs$Name: ["Set as {{name}}", "ตั้งค่าเป็น{{name}}"],
  Score: ["Score", "คะแนน"],
  Search: ["Search", "ค้นหา"],
  "Search $Name": ["Search {{name}}", "ค้นหา{{name}}"],
  "Select right answer": ["Select right answer", "เลือกคำตอบที่ถูกต้อง"],
  Section: ["Section", "ตอนเรียน"],
  Select: ["Select", "เลือก"],
  Selected: ["Selected", "ที่เลือก"],
  "Select?": ["Select {{name}}", "เลือก{{name}}"],
  "Select Answer": ["Select Answer", "เลือกคำตอบ"],
  "Send Reset Password": [
    "Send reset password link to {{email}} success",
    "ส่งลิงก์ในการรีเซตรหัสผ่านไปที่ {{email}} สำเร็จ",
  ],
  Sequence: ["Sequence", "ลำดับ"],
  Setting: ["Setting", "ตั้งค่า"],
  Setting$Name: ["Setting {{name}}", "ตั้งค่า{{name}}"],
  "Sign In": ["Sign In", "เข้าสู่ระบบ"],
  "Sign out": ["Sign out", "ออกจากระบบ"],
  SignOut: ["Sign out", "ออกจากระบบ"],
  Sharing: ["Sharing", "แบ่งปัน"],
  Shuffle: ["Shuffle", "สลับ"],
  Slide: ["Slide", "สไลด์"],
  "Show columns": ["Show columns", "แสดงคอลัมน์"],
  Sorting: ["Sorting", "เรียงลำดับ"],
  Spacing: ["Spacing", "ระยะห่าง"],
  Start: ["Start", "เริ่มต้น"],
  "Start writting or type": ["Start writting or type", "เริ่มการพิมพ์"],
  Status: ["Status", "สถานะ"],
  STUDY: ["STUDY", "เรียน"],
  Student: ["Student", "ผู้เรียน"],
  "Student List": ["Student List", "รายชื่อผู้เรียน"],
  "Sub Question": ["Sub Question", "คำถามย่อยที่"],
  "$Name Successful": ["{{name}} Successful", "{{name}}สำเร็จ"],
  Subject: ["Subject", "หมวดหมู่"],
  Submit: ["Submit", "ส่ง"],
  "Sub Type": ["Sub Type", "ประเภทย่อย"],
  "Student ID": ["Student ID", "รหัสนักเรียน/นิสิต/นักศึกษา"],
  "Student ID Exists": ["Student ID Exists", "รหัสนี้มีอยู่แล้ว"],
  Syllabus: ["Syllabus", "ประมวลรายวิชา"],
  SystemDefault: ["System Default", "ค่าเริ่มต้นของระบบ"],
  Table: ["Table", "ตาราง"],
  "Target Group": ["Target Group", "กลุ่มเป้าหมาย"],
  Task: ["Task", "งาน"],
  TEACH: ["TEACH", "สอน"],
  Teacher: ["Teacher", "ผู้สอน"],
  "Teacher List": ["Teacher List", "รายชื่อผู้สอน"],
  Test: ["Test", "ทดสอบ"],
  Thai: ["Thai", "ไทย"],
  Thumbnail: ["Thumbnail", "รูปขนาดย่อ"],
  Times: ["Times", "ครั้ง"],
  Timezone: ["Timezone", "เขตเวลา"],
  Title: ["Title", "ชื่อ"],
  Top: ["Top", "บน"],
  True: ["True", "ถูก"],
  "True / False": ["True / False", "ถูก / ผิด"],
  Type: ["Type", "ประเภท"],
  TypeHere: ["Type Here", "พิมพ์ทีั่นี่"],
  Undefined: ["Undefined", "ไม่ได้กำหนด"],
  Unsort: ["Unsort", "ยกเลิกการเรียง"],
  Unsubmit: ["Unsubmit", "ยกเลิกการส่ง"],
  Untitled: ["Untitled", "ยังไม่มีชื่อ"],
  Update: ["Update", "อัปเดต"],
  Upload: ["Upload", "อัปโหลด"],
  User: ["User", "ผู้ใช้งาน"],
  Value: ["Value", "ค่า"],
  Vertical: ["Vertical", "แนวตั้ง"],
  Video: ["Video", "วีดิโอ"],
  VDO: ["VDO", "วีดิโอ"],
  Visibility: ["Visibility", "การมองเห็น"],
  Website: ["Website", "เว็บไซต์"],
  WeightedScore: ["Weighted Score", "น้ำหนักคะแนน"],
  Welcome: ["Welcome", "ยินดีต้อนรับ"],
  Width: ["Width", "กว้าง"],
  "You've reached the maximum attempts": [
    "You've reached the maximum attempts",
    "ท่านทำถึงจำนวนครั้งสูงสุดที่ทำได้แล้ว",
  ],
  Yes: ["Yes", "ใช่"],
  You: ["You", "คุณ"],
  /**
   * QuizDisplay
   */
  "Choose to best answer": [
    "Choose to best answer.",
    "ให้เลือกคำตอบที่ถูกต้องที่สุด",
  ],
  "Identify if the following true or false": [
    "Identify if the following true or false.",
    "ให้เลือกว่าข้อความที่ให้มาถูกหรือผิด",
  ],
  "Match the answers to the questions": [
    "Match the answers to the questions.",
    "ให้จับคู่ตัวเลือกกับคำถามให้ถูกต้อง",
  ],
  "Sorting the answer options": [
    "Sorting the answer options.",
    "ให้เรียงลำดับตัวเลือกให้ถูกต้อง",
  ],
  POST: ["POST", "โพสต์"],
  BOOK: ["BOOK", "บุ๊ค"],
  SLIDESHOW: ["SLIDESHOW", "สไลด์โชว์"],
  PROFILE: ["PROFILE", "โปรไฟล์"],
  IMAGES: ["IMAGES", "ภาพ"],
  FILES: ["FILES", "ไฟล์"],
  MAPS: ["MAPS", "แผนที่"],
};

export const getLocale = (lang: string): { [key: string]: string } => {
  const index = ["en", "th"].indexOf(lang);
  if (index > -1) {
    return Object.assign(
      {},
      ...Object.entries(locale_en_th).map(([key, value]) => ({
        [key]: value[index],
      }))
    );
  }
  return {};
};
